CC = gcc
CXX = g++ -std=c++11

CFLAGS = -Wall -O -g
LDFLAGS = -lpthread 
LIB = -L
INC = -I
SOURCES = 
OBJ = file1.o file2.o
TARGET = main

ALL: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o main

file1.o : file1.c file2.h
	$(CXX) $(CFLAGS) -c file1.c -o file1.o

file2.o : file2.c file2.h
	$(CXX) $(CFLAGS) -c file2.c -o file2.o

.PHONY: clean
clean:
	rm -rf *.o $(TARGET)

# all: library.cpp main.cpp
# $@ evaluates to all
# $< evaluates to library.cpp
# $^ evaluates to library.cpp main.cpp
#
# https://blog.csdn.net/ithomer/article/details/5717253
# https://blog.csdn.net/chlele0105/article/details/23960113
# https://seisman.github.io/how-to-write-makefile/introduction.html#id6
