void SLInsert_Sort(SLList &L){
	//æ≤Ã¨¡¥±Ì≤Â»Î≈≈–ÚÀ„∑®
	L.r[0].key=0;L.r[0].next=1;
	L.r[1].next=0; 
	for(i=2;i<=L.length;i++){
		p=0;x=L.r[i].key;
		while(L.r[L.r[p].next].key<x&&L.r[p].next)
			p=L.r[p].next;
		q=L.r[p].next;
		L.r[p].next=i;
		L.r[i].next=q;
	}
	p=L.r[0].next;
	for(i=1;i<L.length;i++){
		while(p<i) 
			p=L.r[p].next;
		q=L.r[p].next;
		if(p!=i){
			L.r[p]<->L.r[i];
			L.r[i].next=p;
		}
		p=q;
	}
}
