void TSMatrixAddto(TSMatrix &A,TSMatrix B){
	//将三元组顺序表存储的矩阵B加到A上
	for(i=1;i<=A.tu;i++)
		A.data[MaxSize-A.tu+i]=A.data[i];
	pa=MaxSize-A.tu+1;
	pb=1;
	pc=1;
	for(x=1;x<=A.mu;x++){//对矩阵的每一行进行加法
		while(A.data[pa].i<x)
			pa++;
		while(B.data[pb].i<x)
			pb++;
		while(A.data[pa].i==x&&B.data[pb].i==x){
			if(A.data[pa].j==B.data[pb].j){
				ne=A.data[pa].e+B.data[pb].e;
				if(ne){
					A.data[pc].i=x;
					A.data[pc].j=A.data[pa].j;
					A.data[pc].e=ne;
					pa++;
					pb++;
					pc++;
				}
			}else if(A.data[pa].j>B.data[pb].j){
				A.data[pc].i=x;
				A.data[pc].j=B.data[pb].j;
				A.data[pc].e=B.data[pb].e;
				pb++;
				pc++;
			}else{
				A.data[pc].i=x;
				A.data[pc].j=A.data[pa].j;
				A.data[pc].e=A.data[pa].e;
				pa++;
				pc++;
			}
		}
		while(A.data[pa]==x){//插入A中的剩余元素
			A.data[pc].i=x;
			A.data[pc].j=A.data[pa].j;
			A.data[pc].e=A.data[pa].e;
			pa++;
			pc++;
		}
		while(B.data[pb]==x){//插入B中的剩余元素
			A.data[pc].i=x;
			A.data[pc].j=B.data[pb].j;
			A.data[pc].e=B.data[pb].e;
			pb++;
			pc++;
		}
	}
	A.tu=pc;
	for(i=A.tu;i<MaxSize;i++)
		A.data[i]={0,0,0};
}